### ISSUE TITLE
Favor de hacer su depósito Git en el REPO

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/redes15#1]
# Espero que lo esten practicando es una herramienta de control de versiones.
Ya terminaron
- [x] Nooo
- [ ] Sii

### Este es subtitulo
*Asterisco es remarcado o italica*

    Python correo.php
    *Desplegar
> ESte es un parrafo enfasis

| Equipo | Sistema Opertivo| Servidor |
|---|---|---|
| # 1 | OpenSUSE | LAMP|

**Comment by paulinanoria** [comment]
@IoTeacher hola profe

**Comment by paulinanoria** [comment]
@tectijuana/redes15 cuando es el examen?

**Comment by ZunigaGabriel** [comment]
@IoTeacher Un saludo al grupo de redes

**Comment by ZunigaGabriel** [comment]
@IoTeacher 
# ejemplo con Markdown

**Comment by paulinanoria** [comment]
# Probando MArkDown 
## Hola

**Comment by paulinanoria** [comment]
|Equipo|**SO**|Servidor|
|---|---|---|
| # 1 | Open surse|Lamp|

- [x] Nooo
- [] siiii

**Comment by paulinanoria** [comment]
- [x] noo
- [ ] sii

**Comment by ZunigaGabriel** [comment]
# Un gato
## Dos Gatos
### Tres Gator

    Otro gato

|Equipo|Sistema|Servidor
|---|---|---|
|# 1| OpenSuse | Lamp |

Terminado ?
- [ ] NO
- [ x] SI

**Comment by ZunigaGabriel** [comment]
Terminado ? **

- [] NO
- [x] SI

**Comment by hrios11210562** [comment]
##Probando probando
