### ISSUE TITLE
CUando quieren el examen?

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/redes15#2]
Que les parece ese dia

**Comment by paulinanoria** [comment]
# Esta bien ese día profe n.n

**Comment by ZunigaGabriel** [comment]
# Acerca del examen U1

Estoy de acuerdo (Y)

**Comment by hrios11210562** [comment]
# Aloha!
## Probando 30 de Septiembre del 2015

**Comment by raulZepeda** [comment]
Sapbee!!
